### ISSUE TITLE
A couple of QoL suggestions.

### ISSUE THREAD

**Issue by Liambass** [SHNecro/ShanghaiJAR#1]
Hi there. 

It'd be nice if running was either toggleable rather having to hold the button, or perhaps run as standard then hold the "run" button to walk.

My other suggestion would be for PMDs to "ask" to be unlocked if you have the appropriate Subchip rather than having to go into the Subchip menu. I guess that would be harder to implement than my other suggestion though.

**Comment by SHNecro** [comment]
Hesitant on the first one, it's how the original games worked(I think, I haven't played in a while) and there's the "fast-running" addon which already makes something sorta like it into a game mechanic.

The PMDs shouldn't be too difficult to do, and I remember the later games did have that feature, so I'll take a look at it.

**Comment by Liambass** [comment]
I thought auto-running _was_ a thing in the original games but I've just checked and you're right. 

That said, my thought process was that if running is a movement option without cost, then players are likely to want to do that most of the time so why bother making them hold a button to do so. 

I do however respect that this is your baby and you want to adhere to certain things. The fact that I've gotta hold a button is basically a non-issue, it was just a small suggestion,

**Comment by SHNecro** [comment]
Oh no, I have zero "grand vision" for this game, I picked up (/ran off with the corpse of) this game from the original creator who himself borrowed a lot (maybe a bit too much) from the original games.
I'm just some random on the internet who played the game and has some free time, I'm afraid of changing anything that might contribute to the "feel" of the game since I have no idea what that "feel" is because I'm no game developer.
That plan went a bit out the window with writing new stuff for the postgame, but it was kinda unavoidable.

The PMD change I think I'll put in, I remember on my first playthrough wondering why that wasn't in.

**Comment by SHNecro** [comment]
Implemented
