### ISSUE TITLE
Fullopen gets deleted

### ISSUE THREAD

**Issue by Nachme** [SHNecro/ShanghaiJAR#10]
Not sure if it's intentional but even if you don't have a duplicate FullOpen addon it gets removed along with the multiple copies of other addons you have. Forgot to note this is going from a save from 0503e4_2 to 0550eWIP4 if thats any useful information.

**Comment by Nachme** [comment]
Forgot to note this is going from a save from 0503e4_2 to 0550eWIP4 if thats any useful information.

**Comment by SHNecro** [comment]
I'll overhaul the retcon message, technically it's removing duplicates but what it's actually doing is replacing one of the duplicates with the new reward a fresh playthrough would find at that location, even if you haven't gotten the 2nd from the "real" location.

It's a little unintuitive, but I felt it beat the odd cases I'd have to handle otherwise, just at the cost of having to explain right it in the message (which I didn't).

**Comment by Nachme** [comment]
Should I upload my save in case mines just a wonky case?

**Comment by SHNecro** [comment]
Sure, it'd be nice just to make sure nothing's gone wrong.

**Comment by Nachme** [comment]
Uploaded it to my google drive
https://drive.google.com/file/d/1sccG3y89RZOGoqzaAH0YhprGSaE3FeTC/view?usp=sharing

**Comment by SHNecro** [comment]
Loaded it up and everything checks out, you can get FullOpen back by exploring the net a bit.

Just checked in the new message for the retcon, hopefully it should clear things up.
