### ISSUE TITLE
Support to Chinese characters?

### ISSUE THREAD

**Issue by darktrident** [SHNecro/ShanghaiJAR#2]
Hello there.

We are doing translation works (to Chinese). The problem is that the game will crash if using Chinese (Both DirectX9 and OpenGL rendering). Could you please add some support to Chinese characters? Thank you!

**Comment by SHNecro** [comment]
This might be a bit tricky to do without some workaround hack that won't look great (but I'll start looking into).
Crashing probably comes from the block characters
![font](https://user-images.githubusercontent.com/55361628/78540112-7dfa7b00-77a8-11ea-891e-e8210ed136d5.png)
which are used for virus names, chip names, and some other places I can't recall.
As you can see, each character has its own graphic which works for English and Japanese because things can be broken down into letters or hiragana/katakana (I think? I used google translate for the Japanese and just picked up bits and pieces).
For Chinese I don't think there's an equivalent, and each character would need to have its own graphic to work the same way as the English and Japanese.
If I'm wrong please let me know, I only have a very basic understanding of Chinese.

As a workaround I can make the game use a fallback if there's no block character, and just print the dialogue-style text in its place (maybe upscaled, outlined, etc.) but it's going to be ugly.
I'll probably have to swap out the font too, I did a quick test and the built-in one doesn't have some of the characters, but it could also be that I don't have the language pack installed for fallback characters.

Side note, I had no idea about this effort, keep up the good work.
Let me know if anything else breaks, the new text system is theoretically designed to support any language-code in the language folder but I never actually tested it.

**Comment by darktrident** [comment]
[AliceRoom and Chips.zip](https://github.com/SHNecro/ShanghaiJAR/files/4439465/AliceRoom.and.Chips.zip)

Thank you for the reply!
This is our translation-test documents. Can you do me a favor that overwrite the origindocuments and have a look, at your spare time? Now we can't even activate the debug mod T_T
Now We use DirectX9 rendering and will crash in the menu/chip page(perhaps its the graphic problem you said.) (And if use OpenGL the game will crash at the beginning...)
Thank you !

**Comment by SHNecro** [comment]
Made a quick fix and I was right, it's ugly. If a character is wider than 8px, it'll start overlapping, but I don't think there's any easy way around that.
-- link obsolete --
There are some missing characters in the bottom left, but it might just be my computer if it's a language pack issue, let me know if it works on yours.

Other improvements/fixes:
- KeyConfig should now be able to see a chinese option in languages if you add a "zh-CN" (or any other language code) folder in "language"
- Map Editor > Open String Browser  should also be able to edit entries in the "zh-CN" folder

Not yet fixed:
- Allowing language packs to set custom images like the title screen or ingame menus, etc.

**Comment by darktrident** [comment]
![QQIMG20200407231400](https://user-images.githubusercontent.com/63183585/78688582-fdfb1f00-7927-11ea-90a5-cb7bc225fc6d.jpg)

Thank you for your help! We activate the game with directX9 and there's no missing characters.  Just a small problem that the characters overlap each other in chip folder ( on the right side of the image it should be "光子炮")

**Comment by SHNecro** [comment]
-- link obsolete --

You're going to have to be careful with spacing, the fallback text is wider than the block characters.
I'll have to start looking into the missing characters in OpenGL and the ability to set language-specific graphics for things like "New Game" and "Continue", but for now you should be able to actually see most of your translations ingame.

Hopefully I'll be able to get those into the next release before you finish translating all of the text.

**Comment by darktrident** [comment]
Hello！
The overlap is repaired when using your x2_Language. But this version, the game will crash in a second.... T_T

**Comment by SHNecro** [comment]
-- link obsolete --

Thank you for finding that bug, turns out it crashed whenever you threw a bomb (or anything tried to play the "throw" sound, since it was actually named "throw_" to avoid the keyword and I removed the hack fix when fixing something else in the sound loading).

Should be fixed now, best of luck with the translation efforts.
Please ignore the half-finished stuff at the end of the game, I made the fix on the in-progress branch.

**Comment by darktrident** [comment]
[Chip.zip](https://github.com/SHNecro/ShanghaiJAR/files/4464074/Chip.zip)
Thank you for the help! But the game still crash when custom chipfolder or open the dictionary...
And this is our testing chip data now

**Comment by SHNecro** [comment]
-- link obsolete --
Thank you and sorry for all the testing you ended up doing.
There was a memory leak in the DirectX9 text measuring code that caused the crash since it was called every frame, but theoretically if you opened and closed the metro screen ~20k times it'd crash too.

**Comment by darktrident** [comment]
Now we can type Chinese characters normally and no crash. Thank you for all the help!

**Comment by darktrident** [comment]
And... What's your game version of Reverse engineering? We found that some chip graphic and floor effect(such as grass floor is just green color) is too simple, so we think your game version maybe...a little old? We have origin game V0.40 if you need? It's better that you can update with it XD
https://github.com/darktrident/SHEJ-4.0
（sorry I'm not practiced with github. In this link, the game is [JAP]ShanghaiEXE_Ver0.40.zip ）

![B8}77LAUNN_B}YJ_% 5{SKS](https://user-images.githubusercontent.com/63183585/79207710-a141bc00-7e73-11ea-902e-560a92a4736a.png)
![_TMQ4CXEPSFYRWB@DHS{O1G](https://user-images.githubusercontent.com/63183585/79207717-a56dd980-7e73-11ea-8c2d-03209fd42505.png)
![6BFTS~LN)B6CRDV08@1FY79](https://user-images.githubusercontent.com/63183585/79207417-41e3ac00-7e73-11ea-9c78-b247cad017f1.png)
![I3J_C0$L~7A)I)0@K}OOTRJ](https://user-images.githubusercontent.com/63183585/79207443-48722380-7e73-11ea-84a1-b360bc0261a1.png)
![KF%EZ`{_Q%N`{Z` 8TVMI@U](https://user-images.githubusercontent.com/63183585/79207464-4c9e4100-7e73-11ea-91af-b00b8efeb4e2.png)
![S0}BEG~LYVIY4%XV {@7N~C](https://user-images.githubusercontent.com/63183585/79207471-4f993180-7e73-11ea-93ce-ab07aa239172.png)

**Comment by SHNecro** [comment]
Thanks for your concern, but this repository was created specifically to use those new graphics.
The previous repository (https://github.com/SHNecro/ShanghaiEXE) was taken down after some people thought the graphics in the original resembled copyrighted characters or were too close to the games it was inspired by.

Some still have access to the original 0.504e graphics files and can restore them by overwriting the "ShaGPattern" and "ShaGResource" files, but these public repositories can't include or link to anywhere they might have been put up to download. Out of respect to the copyright holders.

You will probably be able to find discussion on the topic in places like the 4chan archive yuki.la if you search for "shanghai.exe", but please keep in mind that I have no association with any content posted there.

**Comment by darktrident** [comment]
Thank you! Will there be bugs if I overwrite data with old version? And will there be new graphic remake?
And... Here's a bug(?) report: when viewing Program Advance from menu, each P.A shows only 1 recipe(There should be many combinations to achieve a same P.A). Both in Chinese and Japanese version the recipe loss occurred.

**Comment by SHNecro** [comment]
https://github.com/SHNecro/ShanghaiJAR/releases/download/0503e4/ShanghaiEXE_0503e4_x5_Language.zip
Good catch, again.
It should work correctly now, and I've reverted all the in-progress maps which could cause problems using different graphics versions.
Hopefully I'll have this all ironed out by the next release.
