### ISSUE TITLE
Potentially better battle screen tiles

### ISSUE THREAD

**Issue by AzuraLily** [SHNecro/ShanghaiJAR#6]
Hello, I've been following development of this project for quite some time, and I wanted to offer my help.

I know that due to concerns with potential legal issues with Capcom, you can't use tiles that are close counterparts of Battle Network tiles, but I wanted to offer my services in potentially creating distinct tiles with more detail.

If any of those in charge are interested, I can make some quick early samples of battle screen tiles.

**Comment by SHNecro** [comment]
Hey, thanks for reaching out, it's always great to see interest in this project.

I might not be be able to provide any meaningful feedback or direction (pretty much zero eye for art), but I'd be happy to swap out my 5-second mspaint for any real graphics.

That said, some people may _insist_ on using and sharing alternate versions of the graphics as the "real" version since nobody's quite sure what might (still) bring down a complaint from above, so don't feel pressured to try to make the perfect tile.

Again, I really appreciate the offer and I'll take you up on it in a heartbeat especially for the people who might stumble onto this project in other ways, but I'd hate for you to have put in effort for something people might not end up seeing.

**Comment by AzuraLily** [comment]
It's all good!  Honestly, creating is it's own reward for me.  I'll need to take another look at the tiles already in game, but I think I can do this.

Thanks for the opportunity!

**Comment by AzuraLily** [comment]
I have an early draft.  Is there any way you'd like me to show it for approval?

**Comment by SHNecro** [comment]
If you're alright with it being public you can upload it directly to this issue with drag+drop, or I've got the throwaway email I've been using for these accounts at gMFn4IOyf6zPm9th@protonmail.com (I don't check it all that often since it's a pain to log in to.)

**Comment by AzuraLily** [comment]
Alright, will be doing so within the next day.  Sorry I'm late, been insanely busy with some life curveballs.

**Comment by AzuraLily** [comment]
![Revision](https://user-images.githubusercontent.com/74216957/99935086-dd080280-2d2d-11eb-8d32-9a4a584d8f63.png)
And here the new tiles are.  Gotta say, I want to redo a few of them, especially the grass tiles.  But I feel generally good with how they turned out.

For the Holy tiles, I used the Yin-Yang orbs.  If this makes gameplay harder for whatever reason, please let me know so I can replace them with something more standard-- just wanted to add some Touhou flavor.

**Comment by SHNecro** [comment]
No worries, coming up on a year since the last release I have no room to talk.

If you don't mind, I've made a couple of tweaks to the fire and elec tiles to fit a bit more with how they act ingame (which really shows how much the mspaint placeholders need to be replaced).
![battleobjects](https://user-images.githubusercontent.com/55361628/100039346-e5a61a80-2db9-11eb-9ba0-c3ed7991359b.png)

![editedtiles](https://user-images.githubusercontent.com/55361628/100038298-98757900-2db8-11eb-8eef-a0dd38629bb4.gif)

**Comment by AzuraLily** [comment]
All good!  I very much appreciate the feedback!  Thank you for letting me help!

I have a few other projects to work on, but I'll be coming back to this before long.  Also, shows how long it's been since I played-- mistook the Elec tiles for Holy tiles.  Sorry about that.
